version: 0.2

env:
  variables:
    ECR_REPOSITORY_NAME: demo/api

phases:
  install:
    runtime-versions:
      golang: 1.15
  pre_build:
    commands: 
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION_NAME.amazonaws.com/$ECR_REPOSITORY_NAME
  build:
    commnads:
      - docker build -t $REPOSITORY_URI:latest.
  post_build:
    commands:
      - echo "docker push $REPOSITORY_URI:latest"
      - docker push $REPOSITORY_URI:latest
